name: Med Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1-5'
    - cron: '30 21 * * 1-5'
    - cron: '0 23 * * 1-5'
    - cron: '0 1 * * 2-6'
    - cron: '30 14 * * 0,6'
    - cron: '30 17 * * 0,6'
    - cron: '30 20 * * 0,6'
    - cron: '30 23 * * 0,6'
    - cron: '0 2 * * 0,1'

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Call check-meds
        run: |
          curl -X GET "https://bp-reminder-4383.twil.io/check-meds"
